"""Generate the golden URL/count baseline from the PRE-REFACTOR scrapers.

Run from the repo root, against the untouched legacy scripts, BEFORE any
engine refactor lands:

    .venv/bin/python tests/make_golden.py

Writes tests/golden_urls.json — the frozen regression target consumed by
tests/test_url_parity.py. The baseline locks in, for each route:

  * every generated Google Flights URL across a fixed parameter matrix
    (EgyptAir: the historical 2026-05-27 run params; Turkey: the 12 fixed
    Aug-2026 pairs x IST/SAW/AYT; AMS: 2026-05-27 + 60d daily window), and
  * the pair counts those parameters enumerate.

It also cross-checks the generated URLs byte-for-byte against the URLs
stored in the cached historical run files (results-2026-05-27.json,
dub_turkey_all_results.json, dub_turkey_saw_ayt.json), proving the
enumeration + URL builder reproduce the real recorded runs. Exits non-zero
if any cross-check fails.
"""

from __future__ import annotations

import datetime as dt
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import cheapest_dub_ams as ams  # noqa: E402
import cheapest_dub_cai_egyptair as egyptair  # noqa: E402
import cheapest_dub_turkey as turkey  # noqa: E402

EGYPTAIR_PARAMS = {
    "start": "2026-05-27",
    "window_days": 60,
    "min_trip_days": 3,
    "max_trip_days": 14,
    "weekdays": "Sat,Sun,Tue,Thu",
}
AMS_PARAMS = {
    "start": "2026-05-27",
    "window_days": 60,
    "min_trip_days": 3,
    "max_trip_days": 14,
    "weekdays": "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
}
TURKEY_DESTINATIONS = ["IST", "SAW", "AYT"]


def window_pairs(mod, params: dict) -> list[tuple[dt.date, dt.date]]:
    """Replicate the shared CLI/scanner.py enumeration using the module's own helpers."""
    start = dt.date.fromisoformat(params["start"])
    end = start + dt.timedelta(days=params["window_days"])
    wd = mod._parse_weekdays(params["weekdays"])
    deps = list(mod._valid_days(start + dt.timedelta(days=1), end, wd))
    return [
        (dep, ret)
        for dep in deps
        for ret in mod._valid_days(
            dep + dt.timedelta(days=params["min_trip_days"]),
            dep + dt.timedelta(days=params["max_trip_days"]),
            wd,
        )
    ]


def cross_check(cached_name: str, key_fn, url_map: dict[str, str], label: str) -> bool:
    rows = json.loads((ROOT / cached_name).read_text())
    missing: list[str] = []
    mismatched: list[str] = []
    for row in rows:
        key = key_fn(row)
        if key not in url_map:
            missing.append(key)
        elif url_map[key] != row["url"]:
            mismatched.append(key)
    ok = not missing and not mismatched
    status = "OK " if ok else "FAIL"
    print(f"  [{status}] {label}: {len(rows)} cached rows, "
          f"{len(mismatched)} URL mismatches, {len(missing)} keys not enumerated")
    for key in (mismatched + missing)[:3]:
        print(f"         first offender: {key}")
    return ok


def main() -> int:
    sha = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=ROOT, capture_output=True, text=True
    ).stdout.strip()

    egy_pairs = window_pairs(egyptair, EGYPTAIR_PARAMS)
    egy_urls = {f"{d}|{r}": egyptair.build_url(d, r) for d, r in egy_pairs}

    tur_pairs = turkey.august_2026_pairs()
    tur_urls = {
        f"{dest}|{d}|{r}": turkey.build_url(d, r, dest)
        for dest in TURKEY_DESTINATIONS
        for d, r in tur_pairs
    }

    ams_pairs = window_pairs(ams, AMS_PARAMS)
    ams_urls = {f"{d}|{r}": ams.build_url(d, r) for d, r in ams_pairs}

    print(f"Enumerated: egyptair={len(egy_pairs)} turkey={len(tur_urls)} ams={len(ams_pairs)}")
    print("Cross-checking against cached historical runs:")
    ok = cross_check(
        "results-2026-05-27.json", lambda r: f"{r['dep']}|{r['ret']}", egy_urls, "egyptair vs results-2026-05-27"
    )
    ok &= cross_check(
        "dub_turkey_all_results.json",
        lambda r: f"{r['dest']}|{r['dep']}|{r['ret']}",
        tur_urls,
        "turkey vs dub_turkey_all_results",
    )
    ok &= cross_check(
        "dub_turkey_saw_ayt.json",
        lambda r: f"{r['dest']}|{r['dep']}|{r['ret']}",
        tur_urls,
        "turkey vs dub_turkey_saw_ayt",
    )

    golden = {
        "generated_from_commit": sha,
        "note": "Generated by tests/make_golden.py from the pre-refactor scrapers. Do not regenerate after the engine refactor.",
        "egyptair": {"params": EGYPTAIR_PARAMS, "count": len(egy_pairs), "urls": egy_urls},
        "turkey": {
            "destinations": TURKEY_DESTINATIONS,
            "count": len(tur_urls),
            "pairs": [[d.isoformat(), r.isoformat()] for d, r in tur_pairs],
            "urls": tur_urls,
        },
        "ams": {"params": AMS_PARAMS, "count": len(ams_pairs), "urls": ams_urls},
        "cross_check_passed": ok,
    }
    out = ROOT / "tests" / "golden_urls.json"
    out.write_text(json.dumps(golden, indent=1))
    print(f"Wrote {out} ({out.stat().st_size // 1024} KB), cross_check_passed={ok}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
