"""URL + pair-count parity: engine vs the pre-refactor golden baseline.

Asserts that app.engine reproduces, byte-for-byte, every URL in
tests/golden_urls.json (generated by tests/make_golden.py from the untouched
legacy scrapers), and that pair counts / estimates match. Also exercises the
legacy-signature build_url wrappers on the three shim scripts.

Run standalone (no pytest needed):  .venv/bin/python tests/test_url_parity.py
Or via pytest:                      pytest tests/test_url_parity.py
"""

from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from app import engine  # noqa: E402
from app.route_defs import BUILTIN_ROUTES  # noqa: E402

GOLDEN = json.loads((ROOT / "tests" / "golden_urls.json").read_text())


def _d(s: str) -> dt.date:
    return dt.date.fromisoformat(s)


def test_egyptair_engine_urls() -> None:
    g = GOLDEN["egyptair"]
    route = BUILTIN_ROUTES["egyptair"]
    config = dict(g["params"])
    pairs = engine.enumerate_pairs(route, config)
    assert len(pairs) == g["count"], f"pair count {len(pairs)} != golden {g['count']}"
    built = {
        f"{dep}|{ret}": engine.build_url(dep, ret, dest="CAI", airline="MS")
        for dep, ret in pairs
    }
    assert built == g["urls"], "egyptair engine URLs diverge from golden"
    assert engine.estimate_pairs(route, config) == g["count"]


def test_turkey_engine_urls() -> None:
    g = GOLDEN["turkey"]
    route = BUILTIN_ROUTES["turkey"]
    config = {"destinations": ",".join(g["destinations"])}
    pairs = engine.enumerate_pairs(route, config)
    assert [[d.isoformat(), r.isoformat()] for d, r in pairs] == g["pairs"], (
        "turkey fixed pairs diverge from golden"
    )
    built = {
        f"{dest}|{dep}|{ret}": engine.build_url(dep, ret, dest=dest, airline=None)
        for dest in g["destinations"]
        for dep, ret in pairs
    }
    assert built == g["urls"], "turkey engine URLs diverge from golden"
    assert engine.estimate_pairs(route, config) == g["count"]
    assert engine.destinations_for(route, config) == tuple(g["destinations"])


def test_ams_engine_urls() -> None:
    g = GOLDEN["ams"]
    route = BUILTIN_ROUTES["ams"]
    config = dict(g["params"])
    pairs = engine.enumerate_pairs(route, config)
    assert len(pairs) == g["count"], f"pair count {len(pairs)} != golden {g['count']}"
    built = {
        f"{dep}|{ret}": engine.build_url(dep, ret, dest="AMS", airline=None)
        for dep, ret in pairs
    }
    assert built == g["urls"], "ams engine URLs diverge from golden"
    assert engine.estimate_pairs(route, config) == g["count"]


def test_ams_route_pins_daily_weekdays() -> None:
    """The API path must ignore config weekdays for AMS (legacy behavior)."""
    g = GOLDEN["ams"]
    route = BUILTIN_ROUTES["ams"]
    config = dict(g["params"])
    config["weekdays"] = "Sat,Sun,Tue,Thu"  # ScanCreate default leaks this for every scanner
    assert engine.estimate_pairs(route, config) == g["count"], (
        "AMS estimate must stay daily even when config carries weekdays"
    )


def test_shim_legacy_build_url_signatures() -> None:
    import cheapest_dub_ams as ams
    import cheapest_dub_cai_egyptair as egyptair
    import cheapest_dub_turkey as turkey

    for key, url in GOLDEN["egyptair"]["urls"].items():
        dep, ret = key.split("|")
        assert egyptair.build_url(_d(dep), _d(ret)) == url
    for key, url in GOLDEN["turkey"]["urls"].items():
        dest, dep, ret = key.split("|")
        assert turkey.build_url(_d(dep), _d(ret), dest) == url
    for key, url in GOLDEN["ams"]["urls"].items():
        dep, ret = key.split("|")
        assert ams.build_url(_d(dep), _d(ret)) == url
    assert [d.isoformat() for d, _ in turkey.august_2026_pairs()] == [
        p[0] for p in GOLDEN["turkey"]["pairs"]
    ]


def test_scanner_estimate_total_matches_golden() -> None:
    from app.scanner import estimate_total

    assert estimate_total("egyptair", dict(GOLDEN["egyptair"]["params"])) == GOLDEN["egyptair"]["count"]
    assert estimate_total("turkey", {"destinations": "IST,SAW,AYT"}) == GOLDEN["turkey"]["count"]
    assert estimate_total("ams", dict(GOLDEN["ams"]["params"])) == GOLDEN["ams"]["count"]
    try:
        estimate_total("nope", {})
        raise AssertionError("estimate_total should reject unknown scanner")
    except ValueError as exc:
        assert "Unknown scanner" in str(exc)


if __name__ == "__main__":
    failures = 0
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            try:
                fn()
                print(f"PASS {name}")
            except AssertionError as exc:
                failures += 1
                print(f"FAIL {name}: {exc}")
    sys.exit(1 if failures else 0)
